CREATE DATABASE UPI_ANALYSIS; 
USE UPI_ANALYSIS;

create table customer(
           customer_id int primary key,
           customer_name varchar(50) ,
           age int ,
           gender varchar(10),
           city varchar(10),
           signup_date date,
           bank_id int,
           FOREIGN KEY (bank_id) REFERENCES bank(bank_id))
          ;
           
create table bank(
          bank_id int primary key,
          bank_name varchar(20),
          bank_type varchar(10),
          headquarters_city varchar(20));
          
create table merchant(
                      merchant_id int primary key,
                      merchant_name varchar(20),
                      category varchar(20),
                      city varchar(20));
DROP TABLE TRANSACTION;        
create table transaction(
                         transaction_id int primary key,
                         customer_id int,
                         merchant_id int,
                         transaction_time  TIMESTAMP,
                         amount NUMBER(10,2),
                         payment_method varchar(20),
                         payment_status varchar(20),
                         transaction_type varchar(20),
                         foreign key (customer_id) references customer(customer_id),
                         foreign key (merchant_id) references merchant(merchant_id));
SELECT * FROM CUSTOMER;
select * from transaction;
select * from merchant;
select * from bank;

//Total number of transaction 
select count(transaction_id) from transaction ;

//Total sucessfull transaction
select COUNT(payment_status)
from transaction
where payment_status='Success';

//Total revenue generated
select sum(amount)
from transaction
where payment_status='Success';

//Average transactrion ammount 
select avg(amount)
from transaction
where payment_status='Success'; 

//Highest transaction amount
select max(amount)
from transaction
where payment_status='Success';

//total transaction by payment_status
select payment_status,count(transaction_id) as total_transaction
from transaction 
group by payment_status;

//total revenue by transaction_type
select transaction_type, sum(amount)as total_revenue
from transaction
group by transaction_type;

//top 5 customer by total spending
select customer_id,sum(amount) as total_spending
from transaction
where payment_status='Success'
group by customer_id
order by sum(amount) desc
limit 5;

//top 3 merchants with highest revenue
select merchant_id,sum(amount) as total_revenue
from transaction
where payment_status='Success'
group by merchant_id
order by sum(amount) desc
limit 3;

//which payment method is used mosts
select payment_method,count(payment_method) as total_usage
from transaction
group by payment_method
order by total_usage desc
limit 1;

//peak transaction hour based on total transaction
select hour(transaction_time)as transaction_hour ,count(*)as total_transaction
from transaction
group by transaction_hour
order by total_transaction desc
limit 1;

//which city has highest number of customer?
select city,count(*)as total_customer
from customer
group by city
order by total_customer desc
limit 1;

//which bank has highest number of customer?
select b.bank_name,count(*)as total_customer
from customer c 
join bank b on c.bank_id = b.bank_id
group by b.bank_name
order by total_customer desc
limit 1;

//total revenue generated by each merchant category
select m.category, sum(t.amount) as total_revenue
from transaction t
join merchant m on m.merchant_id = t.merchant_id
where payment_status='Success'
group by category
order by total_revenue desc;

//rank customer based on total spending
select customer_id , sum(amount) as total_revenue,
rank()over ( order by sum(amount) desc) as customer_rank
from transaction
where payment_status='Success'
group by customer_id;

//find cusstomerbwhose total spending is greater then average customer spending
select customer_id,sum(amount) as total_spending
from transaction
where payment_status='Success'
group by customer_id
having sum(amount)>(
 select avg(total_spending)
 from(select customer_id, sum(amount) as total_spending
from transaction
where payment_status='Success'
group by customer_id
)avg_table);

//categorized customer
select customer_id,sum(amount) as total_spending,
case
    when total_spending > 10000 then 'High spender'
    when total_spending between 5000 and 10000 then 'Medium spender'
    else 'Low spender'
    end as customer_categorize
from transaction
where payment_status='Success'
group by customer_id
order by customer_id;

//t0p 3 customer in each city based on total spending
with customer_spending as
(
select c.city,t.customer_id,sum(t.amount)as total_spending
from transaction t
join customer c on c.customer_id = t.CUSTOMER_ID
where payment_status='Success'
and c.city is not null
group by c.city,t.customer_id
)
select city,customer_id,total_spending,
row_number()over(partition by city order by total_spending desc) as rn  
from customer_spending
qualify rn<= 3
; 

//find month over month revenuve growth
WITH monthly_revenue AS
(
    SELECT MONTH(transaction_time) AS month_no,
           SUM(amount) AS revenue
    FROM transaction
    WHERE payment_status = 'Success'
    GROUP BY MONTH(transaction_time)
)

SELECT month_no,
       revenue,
       LAG(revenue) OVER(ORDER BY month_no) AS previous_month_revenue
FROM monthly_revenue;

//top spending customer in each  bank
with top_spending as(
select c.customer_id,b.bank_name,sum(t.amount)as total_spending 
from transaction t 
join customer c on t.CUSTOMER_ID=c.customer_id
join bank b on c.bank_id=b.bank_id
where t.payment_status = 'Success'
group by c.customer_id,b.bank_name
)
select bank_name,customer_id,total_spending
from top_spending
qualify(row_number()over(partition by bank_name order by total_spending desc) )= 1
;

//customer who had made a successful transaction 
SELECT c.customer_id,
       c.customer_name,t.payment_status
FROM customer c
left JOIN transaction t
ON c.customer_id = t.customer_id
AND t.payment_status != 'Success'
;

//Find customers who used more than one payment method.
SELECT 
    c.customer_id,
    c.customer_name,count(distinct t.payment_method) as payment_method_used
FROM transaction t
JOIN customer c 
    ON t.customer_id = c.customer_id
WHERE t.payment_status = 'Success'
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(DISTINCT t.payment_method) > 1;

//Find the Top 5 customers with the highest number of successful transactions.
select c.customer_id,c.customer_name,count(*) as successfull_transaction
from transaction t 
join customer c on c.customer_id = t.CUSTOMER_ID
where t.payment_status = 'Success'
group by c.customer_id,c.customer_name
order by count(t.payment_status) desc
limit 5;

//Find the merchant category with the highest revenue.
select m.merchant_id,m.merchant_name,sum(t.amount) as highest_revenue
from transaction t 
join merchant m on m.merchant_id=t.MERCHANT_ID
where payment_status = 'Success'
group by m.merchant_id,m.merchant_name
order by sum(t.amount) desc
limit 1;

//Find banks whose customers generated more than ₹1,00,000 revenue.
select b.bank_id,
       b.bank_name,
       sum(t.amount) as total_revenue
from transaction t
join customer c 
on t.customer_id = c.customer_id
join bank b 
on c.bank_id = b.bank_id
where payment_status = 'Success'
group by b.bank_id,b.bank_name
having sum(t.amount)>100000; 

//Find the monthly revenue trend based on successful transactions.
select date_trunc('month' ,transaction_time) as month,
       sum(amount) as total_revenue
from transaction 
where payment_status = 'Success'
group by date_trunc('month' ,transaction_time)
order by month;

SELECT 
     month(transaction_time) AS month,
    SUM(amount) AS total_revenue
FROM transaction
WHERE payment_status = 'Success'
GROUP BY  month(transaction_time)
ORDER BY month;

//For each city, show:Total Customers & Total Revenue Generated
SELECT 
    c.city,
    COUNT(DISTINCT c.customer_id) AS total_customers,
    SUM(CASE 
            WHEN t.payment_status = 'Success' 
            THEN t.amount 
            ELSE 0 
        END) AS total_revenue
FROM customer c
LEFT JOIN transaction t
ON c.customer_id = t.customer_id
GROUP BY c.city;

//Find the Top 2 merchants in each category based on revenue.
WITH merchant_revenue AS (
    SELECT 
        m.merchant_name,
        m.category,
        SUM(CASE 
                WHEN t.payment_status = 'Success' 
                THEN t.amount 
                ELSE 0 
            END) AS total_revenue
    FROM transaction t
    JOIN merchant m 
        ON m.merchant_id = t.merchant_id
    GROUP BY m.merchant_name, m.category
)

SELECT 
    merchant_name,
    category,
    total_revenue,
    ROW_NUMBER() OVER (
        PARTITION BY category 
        ORDER BY total_revenue DESC
    ) AS rn
FROM merchant_revenue
QUALIFY rn <= 2;

-- For every customer show:

-- Total Spending
-- Customer Rank (based on spending)
-- Customer Category:
-- High (> 50,000)
-- Medium (20,000–50,000)
-- Low (< 20,000)
WITH customer_spending AS (
    SELECT 
        c.customer_id,
        c.customer_name,
        SUM(CASE 
                WHEN t.payment_status = 'Success' 
                THEN t.amount 
                ELSE 0 
            END) AS total_spending
    FROM customer c
    JOIN transaction t
        ON c.customer_id = t.customer_id
    GROUP BY c.customer_id, c.customer_name
)

SELECT 
    customer_id,
    customer_name,
    total_spending,

    RANK() OVER (
        ORDER BY total_spending DESC
    ) AS customer_rank,

    CASE 
        WHEN total_spending > 50000 THEN 'High Spender'
        WHEN total_spending BETWEEN 20000 AND 50000 THEN 'Medium Spender'
        ELSE 'Low Spender'
    END AS customer_category

FROM customer_spending;









    
         